name: Django CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install "Django>=4.2" pytest pytest-django
        fi

    - name: Run tests
      run: |
        if [ -f manage.py ]; then
          python manage.py migrate --noinput
          python manage.py test -v 2
        else
          pytest -q
        fi
